<?php

/**
 * Model_Groups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Project
 * @subpackage Sub project
 * @author     Company <info@company.com>
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Model_Groups extends Model_Base_Groups
{

}